### ISSUE TITLE
Using mysql will throw some errors

### ISSUE THREAD

**Issue by Zauberstuhl** [ganggo/ganggo#17]
- [x] data too long
- [x] incorrect datetime
 
```
ERROR 2017/07/15 08:00:19 receiver.go:125: Error 1292: Incorrect datetime value: '1970-01-01 00:00:00' for column 'birthday' at row 1

ERROR 2017/07/15 07:59:43 receiver.go:125: Error 1406: Data too long for column 'bio' at row 1 {3 2017-07-13 22:

Error 1406: Data too long for column 'author_signature' at row 1
```

**Comment by Zauberstuhl** [comment]
The datetime should be fixed and future errors can be resolved with the migration functionality introduced in https://github.com/ganggo/ganggo/commit/2991832df1e2602b03241f13a89eec5115dba0cc
